---
- hosts: 127.0.0.1
  vars_files: 
    - vault
    - vars.yml
  tasks:
    - name: Delete the .storage folder
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /root/.homeassistant/.storage/
        - /root/.homeassistant/home-assistant.log
        - /root/.homeassistant/.HA_VERSION
        - /root/.homeassistant/deps/
        
    - name: Template for configs
      template:
        src: "{{ item }}.j2"
        dest: "/root/.homeassistant/{{ item }}"
      with_items:
        - configuration.yaml
        - automations.yaml
        - binary_sensor.yaml
        - customize.yaml
        - groups.yaml
        - scenes.yaml
        - scripts.yaml
        - sensors.yaml
        - switch.yaml
        - secrets.yaml
...