FROM registry.fedoraproject.org/fedora:36

# Install some packages
RUN dnf install -y python python3-pip python-devel gcc && dnf -y update && \
    python3 -m pip install wheel && pip install homeassistant

#run hass once ignoring errors so the deps folder is populated
RUN timeout 30s hass; exit 0

#expose 8123/tcp for ha
EXPOSE 8123

WORKDIR /root/.homeassistant
CMD ["hass"]