FROM registry.fedoraproject.org/fedora:latest

# Install some packages
RUN dnf install -y python python3-pip python-devel gcc git ansible && pip install homeassistant

#run hass once ignoring errors so the deps folder is populated
RUN timeout 30s hass; exit 0

#create configs for HA
RUN git clone https://github.com/elajoie/halocal.git
RUN --mount=type=secret,id=vault ansible-playbook --vault-password-file /run/secrets/vault halocal/hass/main.yml

#expose 8123/tcp for ha
EXPOSE 8123

WORKDIR /root/.homeassistant
CMD ["hass"]