FROM registry.fedoraproject.org/fedora:latest

# Install some packages
COPY requirements.txt .
RUN dnf install -y python python3-pip python-devel gcc && pip install -r requirements.txt homeassistant

#run hass once ignoring errors so the deps folder is populated
RUN timeout 30s hass; exit 0

#expose 8123/tcp for ha
EXPOSE 8123

WORKDIR /root/.homeassistant
CMD ["hass"]