---
- hosts: 127.0.0.1
  vars_files: 
    - vault
    - vars.yml
  tasks:
    - name: Template for hass configs
      template:
        src: "{{ item }}.j2"
        dest: "/root/.homeassistant/{{ item }}"
      with_items:
        - configuration.yaml
        - automations.yaml
        - binary_sensor.yaml
        - customize.yaml
        - groups.yaml
        - scenes.yaml
        - scripts.yaml
        - sensor.yaml
        - switch.yaml
        - secrets.yaml
    - name: Template for mosquitto configs
      template:
        src: mosquitto.conf.j2
        dest: "/etc/mosquitto/mosquitto.conf"
...