---
- hosts: localhost
- include_vars: "vault"
- tasks:
  - name: Delete the .storage folder
    file:
      state: absent
      path: /home/elajoie/halocal/.storage/
      
  - name: Template for configs
    template:
      src: "{{ item }}.j2"
      dest: "/home/elajoie/halocal/{{ item }}"
    with_items:
      - configuration.yaml
      - automations.yaml
      - binary_sensor.yaml
      - customize.yaml
      - groups.yaml
      - scenes.yaml
      - scripts.yaml
      - sensor.yaml
      - switch.yaml
      - secrets.yaml
...