config:
frontend:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
mobile_app:
person:
sun:
system_health:
energy:
zone:

homeassistant:
  name: Home
  elevation: !secret elevation
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: Europe/Berlin

mqtt:
  broker: 10.0.0.2
  username: client
  password: !secret mqttpassword
  discovery: false

switch: !include switch.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
automation: !include automations.yaml
stream:
camera:
  - platform: generic
    name: Front Door
    still_image_url: !secret stream_img
    stream_source: !secret stream_url
    verify_ssl: false
