---
- name: Setup Home Automation
  hosts: ha
  gather_facts: false
  remote_user: "{{ ansible_user }}"
  vars_files: 
#    - vault
    - vars.yml
  tasks:
#    - name: Firewall HA Rules
#      ansible.posix.firewalld:
#        port: "{{ item }}"
#        permanent: true
#        state: enabled
#        immediate: yes
#      with_items:
#        - "8123/tcp"
#        - "1883/tcp"
#        - "1883/udp"
#      become: true

    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: mosquitto.service
        enabled: false
      become: true

    - name: Enable service httpd and ensure it is not masked
      ansible.builtin.systemd:
        name: homeassistant.service
        enabled: false
      become: true

   - name: Start and create systemd for both HA and Mosquitto
      ansible.builtin.shell:
        cmd: "systemctl daemon-reload"
      become: true

    - name: Start and create systemd for both HA and Mosquitto
      ansible.builtin.shell:
        cmd: "podman rm --all --force"
      become: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ homedir }}/.homeassistant"
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ homedir }}/.mosquitto"
        state: directory
        mode: '0755'

    - name: Build HA image
      containers.podman.podman_image:
        name: localhost/homeassistant
        tag: latest
        path: "{{ homedir }}/halocal/hass"
      become: true

    - name: Build MQTT image
      containers.podman.podman_image:
        name: localhost/mosquitto
        tag: latest
        path: "{{ homedir }}/halocal/mosquitto"
      become: true

    - name: Template for mosquitto configs
      ansible.builtin.template:
        src: mosquitto.conf.j2
        dest: "{{ homedir }}/.mosquitto/mosquitto.conf"


    - name: Start Mosquitto
      ansible.builtin.shell: "podman run -dt --rm -p 1883:1883 --name mosquitto -v {{ homedir }}/.mosquitto:/etc/mosquitto:Z localhost/mosquitto:latest"
      become: true

    - name: Start HA
      ansible.builtin.shell: "podman run -dt --rm -p 8123:8123 --name homeassistant -v {{ homedir }}/.homeassistant:/root/.homeassistant:Z localhost/homeassistant:latest"
      become: true

    - name: create systemd for Mosquitto
      ansible.builtin.shell: podman generate systemd --new --name mosquitto > /etc/systemd/system/mosquitto.service
      become: true

    - name: Screate systemd for both HA
      ansible.builtin.shell: podman generate systemd --new --name homeassistant > /etc/systemd/system/homeassistant.service
      become: true

    - name: Start systemd for Mosquitto
      ansible.builtin.shell: systemctl enable --now mosquitto.service
      become: true
      notify:
        - "restart ha"
        - "restart mosquitto"

    - name: Start systemd for both HA
      ansible.builtin.shell: systemctl enable --now homeassistant.service
      become: true
      notify:
        - "restart ha"
        - "restart mosquitto"



#    - name: Template for hass configs
#      ansible.builtin.template:
#        src: "{{ item }}.j2"
#        dest: "{{ homedir }}/.homeassistant/{{ item }}"
#      with_items:
#        - configuration.yaml
#        - automations.yaml
#        - binary_sensor.yaml
#        - customize.yaml
#        - groups.yaml
#        - scenes.yaml
#        - scripts.yaml
#        - sensor.yaml
#        - switch.yaml
#        - secrets.yaml


  handlers:
    - name: Restart ha service
      ansible.builtin.service:
        name: homeassistant.service
        state: started
      listen: "restart ha"
      become: true

    - name: Restart mosquitto service
      ansible.builtin.service:
        name: mosquitto.service
        state: reloaded
      listen: "restart mosquitto"
      become: true
...