---
- name: Setup Home Automation
  hosts: ha
  gather_facts: false
  remote_user: "{{ ansible_user }}"
  vars_files: 
#    - vault
    - vars.yml
  tasks:
    - name: Firewall HA Rules
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - "8123/tcp"
        - "1883/tcp"
        - "1883/udp"
      become: true

#podman run -dt --rm -p 1883:1883 --name mosquitto -v /etc/mosquitto:/etc/mosquitto:Z localhost/mosquitto:latest
#podman run -dt --rm -p 8123:8123 --name homeassistant -v /home/admin/.homeassistant:/root/.homeassistant:Z localhost/homeassistant:latest
#podman generate systemd --new --name mosquitto > /etc/systemd/system/mosquitto.service
#podman generate systemd --new --name homeassistant > /etc/systemd/system/homeassistant.service
#systemctl enable --now mosquitto.service
#systemctl enable --now homeassistant.service

#    - name: Build HA image
#      containers.podman.podman_image:
#        name: localhost/homeassistant
#        tag: latest
#        path: "{{ homedir }}/halocal/hass"
    
#    - name: Build MQTT image
#      containers.podman.podman_image:
#        name: localhost/mosquitto
#        tag: latest
#        path: "{{ homedir }}/halocal/mosquitto"

    - name: Start and create systemd service for Home Assistant
      containers.podman.podman_container:
        name: homeassistant
        image: localhost/homeassistant
        state: present
        recreate: yes
        expose:
          - 8123
        volumes:
          - "{{ homedir }}.homeassistant:/root/.homeassistant"
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: always
          time: 120
          names: true
          container_prefix: automation
      become: true
      
#    - name: Create a directory if it does not exist
#      ansible.builtin.file:
#        path: "{{ homedir }}/.homeassistant"
#        state: directory
#        mode: '0755'
#    - name: Create a directory if it does not exist
#      ansible.builtin.file:
#        path: "{{ homedir }}/.mosquitto"
#        state: directory
#        mode: '0755'
#    - name: Template for hass configs
#      ansible.builtin.template:
#        src: "{{ item }}.j2"
#        dest: "{{ homedir }}/.homeassistant/{{ item }}"
#      with_items:
#        - configuration.yaml
#        - automations.yaml
#        - binary_sensor.yaml
#        - customize.yaml
#        - groups.yaml
#        - scenes.yaml
#        - scripts.yaml
#        - sensor.yaml
#        - switch.yaml
#        - secrets.yaml
#    - name: Template for mosquitto configs
#      tansible.builtin.template:
#        src: mosquitto.conf.j2
#        dest: "{{ homedir }}/.mosquitto/mosquitto.conf"

  handlers:
    - name: Restart firewalld service
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      listen: "reload firewall"
      become: true
...