---
- name: Setup Home Automation
  hosts: 127.0.0.1
  remote_user: "{{ ansible_user }}"
  vars_files: 
#    - vault
    - vars.yml
  tasks:
    - name: Firewall HA Rules
      ansible.posix.firewalld:
        port: "{item}"                                                                                                                
        permanent: true                                                                                                               
        state: enabled
      with_items:
        - "8123/tcp"
        - "1883/tcp"
        - "1883/udp"
      notify: "reload firewall"

#    - name: Download fedora image
#      containers.podman.podman_image:
#        name: registry.fedoraproject.org/fedora:latest
#        tag: homeassistant
#        path: /tmp/halocal/hass
    
      
#    - name: Create a directory if it does not exist
#      ansible.builtin.file:
#        path: /root/.homeassistant
#        state: directory
#        mode: '0755'
#    - name: Create a directory if it does not exist
#      ansible.builtin.file:
#        path: /etc/mosquitto
#        state: directory
#        mode: '0755'
#    - name: Template for hass configs
#      ansible.builtin.template:
#        src: "{{ item }}.j2"
#        dest: "/root/.homeassistant/{{ item }}"
#      with_items:
#        - configuration.yaml
#        - automations.yaml
#        - binary_sensor.yaml
#        - customize.yaml
#        - groups.yaml
#        - scenes.yaml
#        - scripts.yaml
#        - sensor.yaml
#        - switch.yaml
#        - secrets.yaml
#    - name: Template for mosquitto configs
#      tansible.builtin.template:
#        src: mosquitto.conf.j2
#        dest: "/etc/mosquitto/mosquitto.conf"

  handlers:
    - name: Restart firewalld service
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      listen: "reload firewall"
...