---
# vars file for haConfig
device:
  - name: fishtanklight
  - name: fishtankpower
  - name: fishtankfilter
  - name: fishtankfeeder
  - name: henniofficelight
  - name: greenlight
  - name: kitchenwest
  - name: kitchennorth
  - name: firstfloorhallsouth
  - name: firstfloorhallnorth
  - name: kitchen
  - name: basementbathroom
  - name: basementhall
  - name: basementstairs
  - name: bluelight
  - name: shedlights
  - name: livingroom
  - name: whitelight
  - name: firstfloorstorage
  - name: firstfloorbathroom
  - name: outsidenorth
  - name: outsidesouth
  - name: outsideeast
  - name: outsidenwest
  - name: outsideswest
  - name: fire_ericsoffice
  - name: serverrackmodem
  - name: gh_growlight
  - name: gh_led

multiswitchdevice:
  - name: heater1

bsensor:
  - name: outsidenorth
  - name: outsidesouth
  - name: outsideeast
  - name: outsidenwest
  - name: outsideswest

motionLights:
  - name: outsidenorth
  - name: outsideeast
  - name: outsidenwest

doorsensor:
  - name: frontdoorsensor
  - name: backdoorsensor
  - name: garagedoorsensor

temp:
  - name: outsidenorth
  - name: outsidesouth
  - name: outsideeast
  - name: outsidenwest
  - name: outsideswest
  - name: gh_led

humidity:
  - name: outsidenorth
  - name: outsidesouth
  - name: outsideeast
  - name: outsidenwest
  - name: outsideswest
  - name: gh_led

watts:
  - name: fishtanklight
  - name: gh_growlight

fishTanks:
  - name: firstFloor
    power: fishtankpower
    filter: fishtankfilter
    feeder: fishtankfeeder
    lights: fishtanklight
